### ISSUE TITLE
ResponseParseException on Valid JSON

### ISSUE THREAD

**Issue by brownmike** [whichdigital/active-rest-client#78] opened 2015-02-28 00:22 UTC
I have an API that is returning valid JSON but I keep getting ActiveRestClient::ResponseParseException when it comes back.

For example, when I inspect the exception body I get this:

    "{\"computer_reports\":[{\"id\":6,\"name\":\"Desktops\"},{\"id\":1,\"name\":\"Automation\"},{\"id\":2,\"name\":\"Build\"},{\"id\":3,\"name\":\"Storage\"},{\"id\":5,\"name\":\"Portables\"}]}"

Which I can then parse just fine with `JSON.parse`

Am I missing something here or is this a bug?

Thanks!

**Comment by andyjeffries** [comment] 2015-03-04 09:09
I just tried pasting this in to one of the automated tests and it parsed just fine.  However, another case where ActiveRestClient::ResponseParseException may be raised is if the API doesn't return a `Content-Type` HTTP header containing at least "json".  Does your API send back that header?

If not, you should be able to use an `after_request` callback to add it in.

**Comment by andyjeffries** [comment] 2015-03-04 09:14
I'm going to close this issue for now (as I can't reproduce it).  Feel free to comment back if it's not working and I'll reopen it.  If it's still not, can you please paste the entirety of your HTTP API response (including all headers) and I'll try to reproduce it using your response.

**Closed by andyjeffries** 2015-03-04 09:14 UTC

**Comment by brownmike** [comment] 2015-03-04 22:45
Ah, you're exactly right about the response header. It was sending back `Content-Type: text/plain;charset=UTF-8`

Thanks for the response!
